export const palette = [
  { name: "DARK RED", hex: "#8b0000" },
  { name: "CRIMSON", hex: "#b22222" },
  { name: "SCARLET", hex: "#ee3224" },
  { name: "VIVID ORANGE", hex: "#de5d3a" },
  { name: "YELLOW", hex: "#f9c22b" },
  { name: "AMBER", hex: "#e98537" },
  { name: "YELLOW ORANGE", hex: "#f3a833" },
  { name: "MOCHA BROWN", hex: "#4d3533" },
  { name: "BROWN", hex: "#6e4c30" },
  { name: "EARTH BROWN", hex: "#a26d3f" },
  { name: "DARK GREEN", hex: "#006554" },
  { name: "EMERALD", hex: "#26854c" },
  { name: "LEAFY", hex: "#5ab552" },
  { name: "LIME", hex: "#9de64e" },
  { name: "TEAL", hex: "#008b8b" },
  { name: "FOREST GREEN", hex: "#62a477" },
  { name: "COBALT", hex: "#3859b3" },
  { name: "CERULEAN", hex: "#3388de" },
  { name: "SKY BLUE", hex: "#0ca8f2" },
  { name: "SLATE BLUE", hex: "#5e5b8c" },
  { name: "CORAL PINK", hex: "#fa6e79" },
  { name: "PEACH PINK", hex: "#ffa2ac" },
  { name: "PALE PINK", hex: "#ffd1d5" },
  { name: "VIVID INDIGO", hex: "#493ac1" },
  { name: "PERIWINKLE", hex: "#6a5cff" },
  { name: "PASTEL PURPLE", hex: "#cc99ff" },
  { name: "PURPLE", hex: "#9a4d76" },
  { name: "LAVENDER", hex: "#deceed" },
  { name: "BEIGE", hex: "#f6e8e0" },
  { name: "BLACK", hex: "#10121c" },
  { name: "SILVER", hex: "#b0a7b8" },
  { name: "WHITE", hex: "#fafdff" }
]
